// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hotel struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Location string `json:"location"`
}

type Check struct {
	HotelID string `json:"hotelId"`
}

type NewHotel struct {
	Name     string `json:"name"`
	Location string `json:"location"`
}
